### ISSUE TITLE
Missing data files

### ISSUE THREAD

**Issue by smcio** [billyblu2000/Chorderator#1]
Hi there @billyblu2000,

Looks like very cool work you're doing here - thanks 🙂 

I tried to run your project, and I found that several data files required to be in the 'chorderator/static' directory are missing (as per your .gitignore file). For example, the 'chorderator/static/model_master_final.pt' seems to be missing, as also 'chorderator/static/phrase_data0714.npz' and 'edge_weights_0714.npz'.

Would you be able to share these files by any chance please? It'd be great to try out your project 🙂 

Thanks & all the best,
Shaun

**Comment by billyblu2000** [comment]
Sure. Sorry currently the code is not very neat and there might be bugs. I will refine the code soon and upload the missing files in this week or in the coming week.

**Comment by billyblu2000** [comment]
Sure. Sorry currently the code is not very neat and there might be bugs. I
will refine the code soon and upload the missing files in this week or in
the coming week.

**Comment by smcio** [comment]
> Sure. Sorry currently the code is not very neat and there might be bugs. I will refine the code soon and upload the missing files in this week or in the coming week.

Thanks, very much appreciated!

**Comment by billyblu2000** [comment]
Data files link updated in README. I will keep this issue open for several weeks in case there will be any future updates and bugs.

**Comment by smcio** [comment]
Hi @billyblu2000  - thanks for uploading these files - much appreciated.

That has satisfied that dependency, but in running demo.py, I'm also now getting this error:

```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/xxx/AccoMontage2/resource/phrase_split_data/melodies.pk'
```

Looks like the repository seems to be missing a 'phrase_split_data' directory, with a 'melodies.pk' file. Is this a file I need to generate somehow, or might you be able to commit it to the repository/to a file share? :)

Thanks again for your time, and all the best
Shaun

**Comment by billyblu2000** [comment]
> Hi @billyblu2000 - thanks for uploading these files - much appreciated.
> 
> That has satisfied that dependency, but in running demo.py, I'm also now getting this error:
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: '/Users/xxx/AccoMontage2/resource/phrase_split_data/melodies.pk'
> ```
> 
> Looks like the repository seems to be missing a 'phrase_split_data' directory, with a 'melodies.pk' file. Is this a file I need to generate somehow, or might you be able to commit it to the repository/to a file share? :)
> 
> Thanks again for your time, and all the best Shaun

Hi @smcio, sure no problem, thank you for reporting bugs. 

However, the error you saw is probably not the true error. Sorry that I catch the true error such that it become a little confusing. I have now deleted that catch and throw out the true error directly. 

**The true error is probably: AccoMontage2 cannot find the input melody. Please check the the path and the name is correct.**

And this might be because I provided a wrong path in the demo. I have now updated the path in the demo, together with the tonic, note shift information. Please check it out.

Melody path can be specify with the format like:
```python
import chorderator as cdt
cdt.set_melody('MIDI demos/inputs/hpps65/melody.mid')
```

Hope this will solve the problem.

billyblu

**Comment by smcio** [comment]
Thanks @billyblu2000  - those changes did indeed fix the problem. Thanks again for your help on this, and great work on your research.

Best,
Shaun

**Comment by billyblu2000** [comment]
> Thanks @billyblu2000 - those changes did indeed fix the problem. Thanks again for your help on this, and great work on your research.
> 
> Best, Shaun

No problem and thank you very much for interesting. 

Issue closed.

billyblu
