### ISSUE TITLE
Generating with custom melody

### ISSUE THREAD

**Issue by asigalov61** [billyblu2000/Chorderator#2]
Hello,

First of all, I wanted to thank you very much for your great work! Its awesome and I really like it. :)

I have a question... Is it possible to generate output with a custom melody? Or is it not supported yet?

I tried replacing melody.mid with my own midi but it does not work. 

I attached my midi file for your review and your help with this issue would be really appreciated.

Thank you.

Here is the error I am getting on my midi:
[melody.zip](https://github.com/billyblu2000/AccoMontage2/files/9483326/melody.zip)

`@Chorderator 2022-09-03 20:12:51,076 - INFO -  Melody length 4, generate progression with 63 templates 
no matched length
Traceback (most recent call last):
  File "demo.py", line 14, in <module>
    cdt.generate_save(demo_name + '_output_results')
  File "/content/AccoMontage2/chorderator/interaction.py", line 91, in generate_save
    return _core.generate_save(output_name=output_name, task=task, log=log, wav=wav, **kwargs)
  File "/content/AccoMontage2/chorderator/core.py", line 392, in generate_save
    log=True, **kwargs)
  File "/content/AccoMontage2/chorderator/core.py", line 361, in generate
    gen = self.run(cut_in, cut_in_arg, with_texture, **kwargs)
  File "/content/AccoMontage2/chorderator/core.py", line 294, in run
    **kwargs)
  File "/content/AccoMontage2/chorderator/utils/pipeline.py", line 53, in send_in
    progression_list = self.__main_model(splited_melo, self.meta)
  File "/content/AccoMontage2/chorderator/utils/pipeline.py", line 78, in __main_model
    processor.solve()
  File "/content/AccoMontage2/chorderator/utils/models/DP.py", line 153, in solve
    max_score = max([self._dp[-1][i][1] for i in range(min([self.max_num, len(templates[-1])]))])
ValueError: max() arg is an empty sequence`

**Comment by billyblu2000** [comment]
Hi @asigalov61,

Thank you very much for interesting. AccoMontage2 does support custom melody. However, there are some restrictions.

1. Melody has to be monophonic. That is to say, AccoMontage2 expects only one note will be playing at any time in the melody track. Your melody seems to have multiple voices, and that might cause AccoMonatge2 to produce unexpected results.
2. Only phrases of 4 bars and 8 bars are supported. 
3. Triple meters are not supported.

Could you please provide your generate parameters, inlcude `segmentation`, `tonic` and `mode` such that I can reproduce your situation? Thank you.

billyblu

**Comment by billyblu2000** [comment]
In addition, AccoMontage2 is mainly designed for pop music. Usually for pop music, melodies are monophonic and have simple structures (4-bar phrases and 8-bar phrases). Although music other than pop music is also supported, the result might not be very satisfying. 

billybly

**Comment by asigalov61** [comment]
@billyblu2000 Hey Billy,

Thank you so much for your quick and helpful detailed response.

I am a complete noob to your AccoMontage2, so please forgive me if I am not making sense...

I simply used the original demo.py for all the settings and I simply replaced melody.mid in the default source folder. I also did it in Gogole Colab, although it seems to work well with the original example melodies.

What I was mostly trying to ask is how do I prep my melody.mid file? It seems that each example/source melody.mid comes with extra files/data... How do I generate these files for my custom melody?

And I got it re: melody being monophonic and pop so I can try some other melodies I have that fit these requirements. But I need to know how to prep the source data/folder?

Hope this makes sense to you.

Most sincerely,

Alex

**Comment by billyblu2000** [comment]
Hi @asigalov61 Alex,

Sure no problem. Here are some suggestions that might be helpful.

#### Melody preparation

The only file that AccoMontage2 needed is the melody MIDI file. Those files in folder `MIDI demos/input/*` are not necessary, as most of them are used for conducting experiments in our paper (baseline methods and hyperparameters tuning).

Here is some advice on `melody.mid`:

1. Monophonic.
2. 4/4 time or 2/4 time.
3. Recommend pop music.
4. Phrase of 4 bars and 8 bars.
5. Specify the tempo in the MIDI file, as this might be a reference for AccoMontage2. But if there are tempo changes (ie. change from 80 bpm -> 90 bpm), things might become a little tricky, and I am not very sure how will the program behave. So I recommend the melody have a consistent tempo.

#### Generation Parameters

Although most of the files in `MIDI demos/input/*` are not necessary, `meta.json` is somewhat important. It stores the meta information of this melody, for example, tonic, mode, segmentation, etc. AccoMontage2 won't read this file when running, but you must specify this information before running. I recommend you refer to `README.md`. Here are some detailed explanations. 

`cdt.set_melody('melody.mid')` specifies the melody path. **This is required before generating.**

`cdt.set_meta(tonic=cdt.Key.C, mode=cdt.Mode.MAJOR)` specifies the tonic and mode. If your melody is in C Major, then you should write like this. **This is required before generating.**

`cdt.set_segmentation('A8A8B8B8')` specifies the segmentation (phrases). 'A8A8B8B8' means the melody has 4 phrases, each of them having 8 bars. The first two are phrase A, the last two are phrase B. If two phrases have the same name (A or B or C...), they are expected to be similar (have similar melody progressions). **This is required before generating.**

`cdt.set_texture_prefilter()` and `cdt.set_output_style()` controls the generating styles. Please refer to `README.md`. These are **NOT** required.

Changing only the melody path is not sufficient before generating. AccoMontage2 requires this information to output a more satisfiable result. If you are still confused, I recommend you to look into the demos in `MIDI demos/input/*`, these `melody.mid` files work correctly and `meta.json` files provides the correct meta information. I see no reason why similar formats would cause a crash.

However, there are still several bugs in the program, as we haven't conducted an official test. Please kindly provide the meta information (tonic, mode, and segmentation) you used together with `melody.mid` such that I can reproduce your situation. 

Hope this would help.

Best,
Billy

**Comment by asigalov61** [comment]
@billyblu2000 Thank you so much for such a detailed and helpful response! I will try your suggestions shortly and I will let you know of any problems or if I have any questions.

Thank you again.

Alex

**Comment by asigalov61** [comment]
@billyblu2000 Update: I followed your instructions and I was able to successfully generate chords/accompaniment! :)

Thank you very much for your help and assistance.

I will study your code and I will let you know if I have any more questions/problems.

Thanks

Alex

**Comment by billyblu2000** [comment]
Sure no problem!
