### ISSUE TITLE
Where are files model_master_final.pt and phrase_data0714.npz ?

### ISSUE THREAD

**Issue by taktak1** [billyblu2000/Chorderator#6]
Issue 1 says: https://github.com/billyblu2000/AccoMontage2/issues/1
But I can't find them.
Where are files model_master_final.pt and phrase_data0714.npz ?

**Comment by billyblu2000** [comment]
README provides the [Google Drive link](https://drive.google.com/drive/folders/1z8oW16dZtdS06woHc7_rxserNJRrkc4s?usp=sharing) that stores these files. You have to copy them to path `chorderator/static` manually. The git history became too large so I did not add some data files to git.

**Comment by taktak1** [comment]
Thank you for your response.

**Comment by billyblu2000** [comment]
No problem.
